### ISSUE TITLE
meaning of each folder

### ISSUE THREAD

**Issue by sushant12** [catarse/catarse.js#350]
inside the src/ dir there are 3 different folders. c, root and vm. I know vm is view model. What does the rest of the folder mean?

**Comment by vicnicius** [comment]
Hi, @sushant12! Great to see you here. Hopefully we'll soon have better docs around : )

The structure semantic ideas are like these: 

 - *c* - Small UI components: self-contained javascript módulos that constrain specific UI and behavior
 - *root* - Root components are bigger then regular components. They are the main component and the ones that are mounted (directly or by mithril's router). They also own their data, which should flow in one direction to it's children components (kind of like a [Flux](https://facebook.github.io/flux/) implementation).  In our projects, they are related to endpoints (e.g.: when you hit a /project-permalink endpoint the JS will mount the projectsShow root component).
 - *vm* - As you mentioned, are the view-models. component controllers ideally should not deal with nothing more then the ocmponent's user interface behavior. All other type of data manipulation should be handled by a view-model
 - *c.js* - is just the entry point we use to expose the root components to the application `window.c`
 - *h.js* - a module containing helper methods used across components. stuff like datetime formatting and other types of tasks that are common to all components.
- *error.js* - a module that implements an error interface to be used across components.

Please let me know if the structure semantic is clear and if you have any critics or suggestions regarding the current architecture.

**Comment by sushant12** [comment]
@vicnicius thanks man.
