### ISSUE TITLE
New testing stack

### ISSUE THREAD

**Issue by vicnicius** [catarse/catarse.js#436]
- Make testing extremely simple, so we do not feel tempted to skip tests when writing new code.

**Comment by vicnicius** [comment]
Maybe https://facebook.github.io/jest/ could help with that.

**Comment by pygy** [comment]
Ospec has a tiny API and thus a very low cognitive overhead, even if it means that the tests are a bit more verbose (only four kinds of assertion: `equals`, `deepEquals`, and their negations, no "return a promise magic" for async tests...).
